// "use client";
import "./globals.css";
import { redirect } from "next/navigation";
import { Noto_Sans_Arabic } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { getSession } from "@/lib/auth";
import { headers } from "next/headers";

const notoNaskhArabic = Noto_Sans_Arabic({
  weight: "500",
  subsets: ["arabic"],
  display: "swap",
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = await getSession();
  // if (user && user.role === "admin") {
  // }

  return (
    <html suppressHydrationWarning lang="en" dir="rtl">
      <body className={cn(notoNaskhArabic.className)}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
